### ISSUE TITLE
Unhandled exception executing command 'ticket-resolve'

### ISSUE THREAD

**Issue by InsaneJ** [Jadedwolf/TakeaNumber#5]
Using TakeaNumber 0.7 and Cauldron-MCPC-Plus version git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

I get the following error when trying to resolve a ticket:

```
[18:32:58] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ticket-resolve' in plugin TakeaNumber v0.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1350) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1132) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.util.MissingFormatArgumentException: Format specifier '2$s'
        at java.util.Formatter.format(Formatter.java:2493) ~[?:1.7.0_71]
        at java.util.Formatter.format(Formatter.java:2423) ~[?:1.7.0_71]
        at java.lang.String.format(String.java:2790) ~[?:1.7.0_71]
        at me.olddragon.takeanumber.Messages.getString(Messages.java:74) ~[?:?]
        at me.olddragon.takeanumber.Messages.sendMessage(Messages.java:95) ~[?:?]
        at me.olddragon.takeanumber.TakeaNumber.cmdResolve(TakeaNumber.java:466) ~[?:?]
        at me.olddragon.takeanumber.TakeaNumber.onCommand(TakeaNumber.java:220) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 13 more
```

I first assigned the ticket to myself which worked. Then I tried to resolve the ticket with a commend resulting in the above error. After that the ticket is not resolved.

**Comment by OldDragon2A** [comment]
Hmm, looks like one of the resolve messages is formatted incorrectly.  That '2$s' should be '%2$s'.
